apiVersion: v1
kind: Service
metadata:
  name: serverless-m-service
spec:
  selector:
    app: serverless-m
  ports:
    - protocol: TCP
      port: 5110
      targetPort: 5110
  # type: LoadBalancer
